---
- hosts: webservers
  remote_user: ubuntu
  become_method: sudo
  become: True
  tasks:
    - name: update
      apt: update_cache=yes   
   
    - name: Install tomcat
      apt: name=httpd state=latest

    - name: Start Apache server
      service:
        name: httpd
        state: started
        enabled: True
    - name: Deploy static website
      copy:
        src: index.html
        dest: /var/www/html/
...
